version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_INTERNAL: INSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093
      KAFKA_LISTENER_PORT_INTERNAL: 9093
      KAFKA_LISTENER_NAME_EXTERNAL: EXTERNAL
      KAFKA_ADVERTISED_LISTENER: EXTERNAL://localhost:9092
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092
      KAFKA_LISTENER_PORT_EXTERNAL: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
